// Temporary declaration to satisfy TypeScript until backend regenerates official types
// Do NOT edit autogenerated files; this shim is safe to keep.
export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  public: {
    Tables: {
      contact_messages: {
        Row: {
          id: string
          created_at: string
          read: boolean
          email: string
          subject: string
          message: string
          first_name: string
          last_name: string
        }
        Insert: {
          id?: string
          created_at?: string
          read?: boolean
          email: string
          subject: string
          message: string
          first_name: string
          last_name: string
        }
        Update: {
          id?: string
          created_at?: string
          read?: boolean
          email?: string
          subject?: string
          message?: string
          first_name?: string
          last_name?: string
        }
        Relationships: []
      }
    }
    Views: Record<string, never>
    Functions: Record<string, never>
    Enums: Record<string, never>
    CompositeTypes: Record<string, never>
  }
}
